version: 2
updates:
  # Enable version updates for Ruby dependencies
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "your-username" # Replace with actual GitHub username
    assignees:
      - "your-username" # Replace with actual GitHub username
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "ruby"
    # Group patch updates together
    groups:
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
      security-updates:
        patterns:
          - "*"
        dependency-type: "production"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "your-username" # Replace with actual GitHub username
    assignees:
      - "your-username" # Replace with actual GitHub username
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "your-username" # Replace with actual GitHub username
    assignees:
      - "your-username" # Replace with actual GitHub username
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
