service: slack-github-threads
image: your-username/slack-github-threads
servers:
  web:
    - your-server-ip
proxy:
  ssl: true
  host: your-domain.com
registry:
  server: ghcr.io
  username: your-registry-username
  password:
    - KAMAL_REGISTRY_PASSWORD
env:
  secret:
    - GITHUB_TOKEN
    - SLACK_BOT_TOKEN
builder:
  arch: amd64
